# Build a Regression Model in Keras

## Part A. Build a baseline model (5 marks)
Use the Keras library to build a neural network with the following:
- One hidden layer of 10 nodes, and a ReLU activation function
- Use the adam optimizer and the mean squared error as the loss function.
1. Randomly split the data into a training and test sets by holding 30% of the data for testing. You can use the train_test_splithelper function from Scikit-learn.
2. Train the model on the training data using 50 epochs.
3. Evaluate the model on the test data and compute the mean squared error between the predicted concrete strength and the actual concrete strength. You can use the mean_squared_error function from Scikit-learn.
4. Repeat steps 1 - 3, 50 times, i.e., create a list of 50 mean squared errors.
5. Report the mean and the standard deviation of the mean squared errors.

In [1]:
import pandas as pd
import numpy as np

In [3]:
concrete_data = pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
concrete_data.shape

(1030, 9)

In [5]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64


The data is now clean and ready to use to build our model.

We divide the data into predictors and targets.
The target variable is the strength of the concrete sample.
Therefore, our predictors will be all the other columns.

In [7]:
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

## Import Keras

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [13]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=42)

## Train and Test the Network¶
Let's call the function now to create our model.

In [16]:
# build the model
model = regression_model()

In [17]:
# fit the model
epochs = 50
model.fit(X_train, y_train, epochs=epochs, verbose=1)

Epoch 1/50
721/721 [==============================] - 1s 906us/step - loss: 3410.5200
Epoch 2/50
721/721 [==============================] - 0s 414us/step - loss: 2209.27030s - loss: 2318.
Epoch 3/50
721/721 [==============================] - 0s 473us/step - loss: 1571.9225
Epoch 4/50
721/721 [==============================] - 0s 389us/step - loss: 1091.7527
Epoch 5/50
721/721 [==============================] - 0s 419us/step - loss: 756.3089
Epoch 6/50
721/721 [==============================] - 0s 465us/step - loss: 520.7700
Epoch 7/50
721/721 [==============================] - 0s 386us/step - loss: 373.4229
Epoch 8/50
721/721 [==============================] - 0s 389us/step - loss: 280.7001
Epoch 9/50
721/721 [==============================] - 0s 411us/step - loss: 231.5980
Epoch 10/50
721/721 [==============================] - 0s 471us/step - loss: 201.7396
Epoch 11/50
721/721 [==============================] - 0s 387us/step - loss: 183.4939
Epoch 12/50
721/721 [==============================] - 0s 411us/step - loss: 168.8517
Epoch 13/50
721/721 [==============================] - 0s 386us/step - loss: 158.2825
Epoch 14/50
721/721 [==============================] - 0s 364us/step - loss: 149.3694
Epoch 15/50
721/721 [==============================] - 0s 364us/step - loss: 142.7315
Epoch 16/50
721/721 [==============================] - 0s 363us/step - loss: 137.9230
Epoch 17/50
721/721 [==============================] - 0s 501us/step - loss: 132.4051 0s - loss: 119.7
Epoch 18/50
721/721 [==============================] - 0s 364us/step - loss: 129.4622
Epoch 19/50
721/721 [==============================] - 0s 365us/step - loss: 130.3743
Epoch 20/50
721/721 [==============================] - 0s 415us/step - loss: 125.4417
Epoch 21/50
721/721 [==============================] - 0s 418us/step - loss: 122.2053 0s - loss: 124.30
Epoch 22/50
721/721 [==============================] - 0s 438us/step - loss: 120.1962
Epoch 23/50
721/721 [==============================] - 0s 362us/step - loss: 121.3786
Epoch 24/50
721/721 [==============================] - 0s 467us/step - loss: 120.8728
Epoch 25/50
721/721 [==============================] - 0s 390us/step - loss: 124.1548
Epoch 26/50
721/721 [==============================] - 0s 417us/step - loss: 117.7201 0s - loss: 111.41
Epoch 27/50
721/721 [==============================] - 0s 358us/step - loss: 117.9037
Epoch 28/50
721/721 [==============================] - 0s 387us/step - loss: 115.5732
Epoch 29/50
721/721 [==============================] - 0s 386us/step - loss: 115.2815
Epoch 30/50
721/721 [==============================] - 0s 372us/step - loss: 115.1186
Epoch 31/50
721/721 [==============================] - 0s 394us/step - loss: 114.2382
Epoch 32/50
721/721 [==============================] - 0s 360us/step - loss: 122.6613
Epoch 33/50
721/721 [==============================] - 0s 393us/step - loss: 114.2215
Epoch 34/50
721/721 [==============================] - 0s 410us/step - loss: 113.5008
Epoch 35/50
721/721 [==============================] - 0s 364us/step - loss: 112.8828
Epoch 36/50
721/721 [==============================] - 0s 392us/step - loss: 112.4189
Epoch 37/50
721/721 [==============================] - 0s 469us/step - loss: 115.5703
Epoch 38/50
721/721 [==============================] - 0s 362us/step - loss: 112.0907
Epoch 39/50
721/721 [==============================] - 0s 385us/step - loss: 112.0254
Epoch 40/50
721/721 [==============================] - 0s 366us/step - loss: 114.1292
Epoch 41/50
721/721 [==============================] - 0s 418us/step - loss: 112.9751
Epoch 42/50
721/721 [==============================] - 0s 384us/step - loss: 112.8154
Epoch 43/50
721/721 [==============================] - 0s 397us/step - loss: 112.7387
Epoch 44/50
721/721 [==============================] - 0s 376us/step - loss: 110.6901
Epoch 45/50
721/721 [==============================] - 0s 414us/step - loss: 110.3384
Epoch 46/50
721/721 [==============================] - 0s 391us/step - loss: 111.1546
Epoch 47/50
721/721 [==============================] - 0s 389us/step - loss: 111.7080
Epoch 48/50
721/721 [==============================] - 0s 389us/step - loss: 117.2365
Epoch 49/50
721/721 [==============================] - 0s 385us/step - loss: 112.4027
Epoch 50/50
721/721 [==============================] - 0s 469us/step - loss: 111.9785

In [18]:
loss_val = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss_val

309/309 [==============================] - 0s 376us/step

108.25724538167317

In [19]:
from sklearn.metrics import mean_squared_error

In [20]:
mean_square_error = mean_squared_error(y_test, y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

108.25724736266778 0.0

In [21]:
total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors without normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 113.3033990952575
MSE 2: 120.03774189871878
MSE 3: 115.50043262864394
MSE 4: 122.0201073557042
MSE 5: 129.17822947085483
MSE 6: 107.59919244957588
MSE 7: 137.4218497168285
MSE 8: 98.05477455904568
MSE 9: 130.73878207407338
MSE 10: 108.75311017576544
MSE 11: 102.70996740643646
MSE 12: 102.32402273134892
MSE 13: 115.61377733347871
MSE 14: 116.02681532183897
MSE 15: 108.07901324423386
MSE 16: 107.07382389796976
MSE 17: 127.27991473250404
MSE 18: 97.86009369390297
MSE 19: 96.12969249737687
MSE 20: 115.69681877457208
MSE 21: 100.60555867315496
MSE 22: 101.9094546419903
MSE 23: 112.28240107564093
MSE 24: 108.54513273269998
MSE 25: 110.35001007870177
MSE 26: 101.36610308897149
MSE 27: 128.90089137500158
MSE 28: 108.85547267580495
MSE 29: 109.97186644717713
MSE 30: 113.63747759081399
MSE 31: 134.78368920878685
MSE 32: 106.45196572090815
MSE 33: 105.18894622703972
MSE 34: 109.98779222803208
MSE 35: 113.87943611021566
MSE 36: 154.51695318129455
MSE 37: 130.70230188956154
MSE 38: 119.93703598960704
MSE 39: 116.65229034423828
MSE 40: 114.60848376820388
MSE 41: 123.49439143208625
MSE 42: 113.91055589200609
MSE 43: 110.64573481785055
MSE 44: 107.07916151126997
MSE 45: 117.61861219683897
MSE 46: 120.12611287928708
MSE 47: 115.52348860953619
MSE 48: 113.91318855162191
MSE 49: 101.73593542105172
MSE 50: 110.43706954412862


Below is the mean and standard deviation of 50 mean squared errors without normalized data. Total number of epochs for each training is: 50

Mean: 114.18038038268962
Standard Deviation: 11.228335794883257

## Part B. Normalize the data.

Repeat Part A but use a normalized version of the data. Recall that one way to normalize the data is by subtracting the mean from the individual predictors and dividing by the standard deviation.

How does the mean of the mean squared errors compare to that from Step A?

### The data processed in Part A will be used.

In [28]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [29]:
# build the model
model = regression_model()

In [30]:
# fit the model
epochs = 50
model.fit(X_train, y_train, epochs=epochs, verbose=2)

Epoch 1/50
 - 1s - loss: 31196.9768
Epoch 2/50
 - 0s - loss: 5994.2731
Epoch 3/50
 - 0s - loss: 2873.7457
Epoch 4/50
 - 0s - loss: 2506.3779
Epoch 5/50
 - 0s - loss: 2262.8884
Epoch 6/50
 - 0s - loss: 2103.1882
Epoch 7/50
 - 0s - loss: 1967.2268
Epoch 8/50
 - 0s - loss: 1831.7607
Epoch 9/50
 - 0s - loss: 1715.3973
Epoch 10/50
 - 0s - loss: 1598.6007
Epoch 11/50
 - 0s - loss: 1493.1856
Epoch 12/50
 - 0s - loss: 1396.2718
Epoch 13/50
 - 0s - loss: 1307.0289
Epoch 14/50
 - 0s - loss: 1225.6930
Epoch 15/50
 - 0s - loss: 1149.1879
Epoch 16/50
 - 0s - loss: 1081.8694
Epoch 17/50
 - 0s - loss: 1017.9197
Epoch 18/50
 - 0s - loss: 965.3852
Epoch 19/50
 - 0s - loss: 910.0579
Epoch 20/50
 - 0s - loss: 860.7394
Epoch 21/50
 - 0s - loss: 815.2629
Epoch 22/50
 - 0s - loss: 771.8378
Epoch 23/50
 - 0s - loss: 731.1172
Epoch 24/50
 - 0s - loss: 694.2639
Epoch 25/50
 - 0s - loss: 656.3969
Epoch 26/50
 - 0s - loss: 622.2859
Epoch 27/50
 - 0s - loss: 589.1834
Epoch 28/50
 - 0s - loss: 555.8195
Epoch 29/50
 - 0s - loss: 523.9770
Epoch 30/50
 - 0s - loss: 496.7343
Epoch 31/50
 - 0s - loss: 470.2793
Epoch 32/50
 - 0s - loss: 445.5952
Epoch 33/50
 - 0s - loss: 423.6455
Epoch 34/50
 - 0s - loss: 404.8504
Epoch 35/50
 - 0s - loss: 383.5866
Epoch 36/50
 - 0s - loss: 364.8155
Epoch 37/50
 - 0s - loss: 347.4487
Epoch 38/50
 - 0s - loss: 330.4366
Epoch 39/50
 - 0s - loss: 314.1785
Epoch 40/50
 - 0s - loss: 301.4713
Epoch 41/50
 - 0s - loss: 287.8509
Epoch 42/50
 - 0s - loss: 276.2188
Epoch 43/50
 - 0s - loss: 264.4695
Epoch 44/50
 - 0s - loss: 254.2983
Epoch 45/50
 - 0s - loss: 243.6193
Epoch 46/50
 - 0s - loss: 234.9364
Epoch 47/50
 - 0s - loss: 225.3028
Epoch 48/50
 - 0s - loss: 216.6307
Epoch 49/50
 - 0s - loss: 209.0799
Epoch 50/50
 - 0s - loss: 203.5549

In [31]:
loss_val = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss_val

309/309 [==============================] - 0s 438us/step

174.31302482333385


Now we need to compute the mean squared error between the predicted concrete strength and the actual concrete strength.
Let's import the mean_squared_error function from Scikit-learn.

In [32]:
from sklearn.metrics import mean_squared_error

In [33]:
mean_square_error = mean_squared_error(y_test, y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

174.31303047466525 0.0

In [34]:
total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors with normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 379.95558240575696
MSE 2: 224.31659666388552
MSE 3: 144.70386221185086
MSE 4: 136.53825746307868
MSE 5: 133.94033996186982
MSE 6: 105.90469839349149
MSE 7: 107.85695092654923
MSE 8: 74.89886052400163
MSE 9: 81.01828099223016
MSE 10: 69.6753544730276
MSE 11: 64.99381088207454
MSE 12: 58.57402250913355
MSE 13: 60.3731650380255
MSE 14: 59.54506657424482
MSE 15: 48.5626659701943
MSE 16: 42.282181995972074
MSE 17: 44.91949185738672
MSE 18: 42.13322795633359
MSE 19: 41.72350600159284
MSE 20: 42.72563176324838
MSE 21: 38.245125458850055
MSE 22: 42.28554543553818
MSE 23: 34.16212941141962
MSE 24: 39.06265139039666
MSE 25: 39.67351796789077
MSE 26: 41.69587060625885
MSE 27: 37.074155924775454
MSE 28: 35.58816493753476
MSE 29: 41.260750051455204
MSE 30: 38.32839755950236
MSE 31: 36.93837298544479
MSE 32: 34.30126433387929
MSE 33: 35.958658977619656
MSE 34: 38.18711633281029
MSE 35: 35.887218265471724
MSE 36: 43.30644986544612
MSE 37: 35.431373164105956
MSE 38: 40.02892221987826
MSE 39: 36.82331665434112
MSE 40: 32.2903090973888
MSE 41: 39.98939473420671
MSE 42: 30.90607330174122
MSE 43: 35.81086100112273
MSE 44: 40.27224959833337
MSE 45: 37.86805695468939
MSE 46: 37.37049143522688
MSE 47: 34.37248364544224
MSE 48: 36.53626999345798
MSE 49: 37.25394271801205
MSE 50: 37.67876573828046


Below is the mean and standard deviation of 50 mean squared errors with normalized data. Total number of epochs for each training is: 50

Mean: 61.78458835866699
Standard Deviation: 58.302924155980946


## Part C. Increate the number of epochs.
Repeat Part B but use 100 epochs this time for training.

In [36]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [37]:
# build the model
model = regression_model()

In [38]:
# fit the model
epochs = 50
model.fit(X_train, y_train, epochs=epochs, verbose=2)

Epoch 1/50
 - 1s - loss: 1638.5101
Epoch 2/50
 - 0s - loss: 1623.1081
Epoch 3/50
 - 0s - loss: 1608.9098
Epoch 4/50
 - 1s - loss: 1595.4629
Epoch 5/50
 - 0s - loss: 1582.4851
Epoch 6/50
 - 0s - loss: 1570.1421
Epoch 7/50
 - 0s - loss: 1557.8694
Epoch 8/50
 - 0s - loss: 1545.7922
Epoch 9/50
 - 0s - loss: 1533.6121
Epoch 10/50
 - 0s - loss: 1521.2438
Epoch 11/50
 - 0s - loss: 1508.5873
Epoch 12/50
 - 0s - loss: 1495.5985
Epoch 13/50
 - 0s - loss: 1482.1934
Epoch 14/50
 - 0s - loss: 1468.1103
Epoch 15/50
 - 0s - loss: 1453.7647
Epoch 16/50
 - 0s - loss: 1438.6528
Epoch 17/50
 - 0s - loss: 1422.7727
Epoch 18/50
 - 0s - loss: 1406.3970
Epoch 19/50
 - 0s - loss: 1388.9451
Epoch 20/50
 - 0s - loss: 1370.6381
Epoch 21/50
 - 0s - loss: 1351.2693
Epoch 22/50
 - 0s - loss: 1330.9360
Epoch 23/50
 - 0s - loss: 1309.4688
Epoch 24/50
 - 0s - loss: 1286.3943
Epoch 25/50
 - 0s - loss: 1262.2210
Epoch 26/50
 - 0s - loss: 1237.2016
Epoch 27/50
 - 0s - loss: 1211.1200
Epoch 28/50
 - 0s - loss: 1184.3667
Epoch 29/50
 - 0s - loss: 1156.8853
Epoch 30/50
 - 0s - loss: 1128.7987
Epoch 31/50
 - 0s - loss: 1100.8373
Epoch 32/50
 - 0s - loss: 1072.0872
Epoch 33/50
 - 0s - loss: 1043.9948
Epoch 34/50
 - 0s - loss: 1015.5767
Epoch 35/50
 - 0s - loss: 987.2553
Epoch 36/50
 - 0s - loss: 959.2201
Epoch 37/50
 - 0s - loss: 931.2295
Epoch 38/50
 - 0s - loss: 904.0483
Epoch 39/50
 - 0s - loss: 876.9522
Epoch 40/50
 - 0s - loss: 850.2575
Epoch 41/50
 - 0s - loss: 824.4448
Epoch 42/50
 - 0s - loss: 798.6092
Epoch 43/50
 - 0s - loss: 773.8065
Epoch 44/50
 - 0s - loss: 749.5908
Epoch 45/50
 - 0s - loss: 725.7463
Epoch 46/50
 - 0s - loss: 703.1383
Epoch 47/50
 - 0s - loss: 680.4983
Epoch 48/50
 - 0s - loss: 659.1225
Epoch 49/50
 - 0s - loss: 638.0264
Epoch 50/50
 - 0s - loss: 618.1187

In [39]:
loss_val = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss_val

309/309 [==============================] - 0s 557us/step

630.2178113622573

Now we need to compute the mean squared error between the predicted concrete strength and the actual concrete strength.
Let's import the mean_squared_error function from Scikit-learn.

In [40]:
from sklearn.metrics import mean_squared_error

In [41]:
total_mean_squared_errors = 50
epochs = 100
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors with normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 112.64187965269613
MSE 2: 75.90250641165427
MSE 3: 42.97948455810547
MSE 4: 38.90945556788768
MSE 5: 38.02001901274746
MSE 6: 39.728796591650706
MSE 7: 40.232402517571806
MSE 8: 31.0754473417708
MSE 9: 33.086950703346226
MSE 10: 32.767567582115
MSE 11: 32.63918566780954
MSE 12: 31.159000365865268
MSE 13: 35.66297858895607
MSE 14: 38.9439767633827
MSE 15: 30.95894285158818
MSE 16: 26.99174074216182
MSE 17: 31.003081954412863
MSE 18: 31.912087622583876
MSE 19: 28.023740700533477
MSE 20: 30.646912775379167
MSE 21: 27.32692196299729
MSE 22: 27.948627768210994
MSE 23: 26.462853243435855
MSE 24: 29.236999005561508
MSE 25: 30.496507977976382
MSE 26: 31.15712740506169
MSE 27: 25.577788843691927
MSE 28: 25.286793520535465
MSE 29: 30.731094101100293
MSE 30: 29.13834000868319
MSE 31: 27.07594820288007
MSE 32: 24.989119983413843
MSE 33: 22.981638800364866
MSE 34: 26.095999301058576
MSE 35: 29.565987299946904
MSE 36: 30.359279749848696
MSE 37: 24.53993673231995
MSE 38: 29.17437998453776
MSE 39: 27.338499853140327
MSE 40: 23.495567297086748
MSE 41: 28.011865628190026
MSE 42: 26.003238684151164
MSE 43: 25.216615911440556
MSE 44: 30.390296170626645
MSE 45: 28.489806054865273
MSE 46: 25.515790908467807
MSE 47: 27.167492474552883
MSE 48: 27.3094420818835
MSE 49: 27.582678909054852
MSE 50: 27.6602453768832


Below is the mean and standard deviation of 50 mean squared errors with normalized data. Total number of epochs for each training is: 100

Mean: 32.51226087966267
Standard Deviation: 13.877829812392573

## Part D. Increase the number of hidden layers (5 marks)

Repeat part B but use a neural network with the following instead:

- Three hidden layers, each of 10 nodes and ReLU activation function.

In [42]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [43]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=42)

In [46]:
# build the model
model = regression_model()

In [47]:
# fit the model
epochs = 50
model.fit(X_train, y_train, epochs=epochs, verbose=2)

Epoch 1/50
 - 1s - loss: 1578.1763
Epoch 2/50
 - 0s - loss: 1559.9998
Epoch 3/50
 - 0s - loss: 1538.6747
Epoch 4/50
 - 0s - loss: 1505.6100
Epoch 5/50
 - 0s - loss: 1451.5959
Epoch 6/50
 - 0s - loss: 1365.1525
Epoch 7/50
 - 0s - loss: 1232.8806
Epoch 8/50
 - 0s - loss: 1047.4391
Epoch 9/50
 - 0s - loss: 805.6065
Epoch 10/50
 - 0s - loss: 544.3020
Epoch 11/50
 - 0s - loss: 343.9186
Epoch 12/50
 - 0s - loss: 250.8203
Epoch 13/50
 - 0s - loss: 225.0653
Epoch 14/50
 - 0s - loss: 213.8107
Epoch 15/50
 - 0s - loss: 206.0896
Epoch 16/50
 - 0s - loss: 199.5977
Epoch 17/50
 - 0s - loss: 194.4989
Epoch 18/50
 - 0s - loss: 190.1063
Epoch 19/50
 - 0s - loss: 185.9819
Epoch 20/50
 - 0s - loss: 181.9940
Epoch 21/50
 - 0s - loss: 179.0165
Epoch 22/50
 - 0s - loss: 176.2602
Epoch 23/50
 - 0s - loss: 173.2375
Epoch 24/50
 - 0s - loss: 170.3680
Epoch 25/50
 - 0s - loss: 168.4062
Epoch 26/50
 - 0s - loss: 165.8032
Epoch 27/50
 - 0s - loss: 163.7854
Epoch 28/50
 - 0s - loss: 161.5450
Epoch 29/50
 - 0s - loss: 159.8298
Epoch 30/50
 - 0s - loss: 157.9727
Epoch 31/50
 - 0s - loss: 156.9712
Epoch 32/50
 - 0s - loss: 154.9253
Epoch 33/50
 - 0s - loss: 153.9817
Epoch 34/50
 - 0s - loss: 151.8402
Epoch 35/50
 - 0s - loss: 150.6917
Epoch 36/50
 - 0s - loss: 149.1865
Epoch 37/50
 - 0s - loss: 147.8897
Epoch 38/50
 - 0s - loss: 146.7090
Epoch 39/50
 - 0s - loss: 145.5231
Epoch 40/50
 - 0s - loss: 144.7613
Epoch 41/50
 - 0s - loss: 143.2355
Epoch 42/50
 - 0s - loss: 142.4650
Epoch 43/50
 - 0s - loss: 141.1486
Epoch 44/50
 - 0s - loss: 140.2490
Epoch 45/50
 - 0s - loss: 139.4373
Epoch 46/50
 - 0s - loss: 138.4340
Epoch 47/50
 - 0s - loss: 137.4180
Epoch 48/50
 - 0s - loss: 137.0235
Epoch 49/50
 - 0s - loss: 135.2642
Epoch 50/50
 - 0s - loss: 134.6589

In [48]:
loss_val = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss_val

309/309 [==============================] - 0s 604us/step

137.25939946344369

In [49]:
from sklearn.metrics import mean_squared_error

In [50]:
total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors with normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 98.91443011830154
MSE 2: 119.4758071405602
MSE 3: 78.73480464108168
MSE 4: 53.443347634621034
MSE 5: 42.090041571064674
MSE 6: 40.0718573165943
MSE 7: 41.04603658139127
MSE 8: 35.05714094291613
MSE 9: 32.11416980286632
MSE 10: 34.18208087069317
MSE 11: 33.123541859747135
MSE 12: 28.145903429938752
MSE 13: 34.9700062884482
MSE 14: 35.29390679516838
MSE 15: 30.46905799668198
MSE 16: 24.424783922707764
MSE 17: 31.740784049419908
MSE 18: 33.301517813722675
MSE 19: 27.455708266076147
MSE 20: 30.49929347856145
MSE 21: 24.258825814453914
MSE 22: 28.2758297349257
MSE 23: 25.27886113534082
MSE 24: 26.40428071500414
MSE 25: 31.911307078734957
MSE 26: 27.98217624059387
MSE 27: 23.016646233962962
MSE 28: 27.309466778653338
MSE 29: 29.9911038049988
MSE 30: 25.36771475535766
MSE 31: 22.677650266480676
MSE 32: 21.520280807149447
MSE 33: 22.415473629355816
MSE 34: 28.235948346579345
MSE 35: 26.85011098917248
MSE 36: 35.10836745080053
MSE 37: 22.45036902936917
MSE 38: 31.515263838289624
MSE 39: 25.986815159374842
MSE 40: 22.70455251156705
MSE 41: 29.0667601897107
MSE 42: 24.968417899122517
MSE 43: 24.87839285841266
MSE 44: 29.128134360205394
MSE 45: 29.1740731544865
MSE 46: 27.128682479117682
MSE 47: 27.844824152085387
MSE 48: 25.24224571425552
MSE 49: 26.219881779939225
MSE 50: 26.48241982259411


Below is the mean and standard deviation of 50 mean squared errors with normalized data. Total number of epochs for each training is: 50

Mean: 33.67898138401668
Standard Deviation: 17.978471020797006